secret: ""

replicaCount: 1

image:
  repository: quay.io/gravitational/drone-fork-approval-extension
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  seccomp.security.alpha.kubernetes.io/pod: runtime/default

podSecurityContext: {}

service:
  type: ClusterIP
  port: 3888

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
