apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-fork-approval-extension.fullname" . }}
  labels:
    {{- include "drone-fork-approval-extension.labels" . | nindent 4 }}
type: Opaque
data:
  DRONE_SECRET: {{ required "A valid secret is required!" .Values.secret | b64enc }}
